 
/* This file was auto-generated by Payload CMS. Do not make changes as they'll be overridden! */

export type Media = {
  id: string;
  alt: string;
  caption?: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type Sessions = {
  id: string;
  title: string;
  slug?: string | null;
  description?: string | null;
  sessionType: 'keynote' | 'workshop' | 'panel' | 'lightning' | 'break';
  speakers?: string[] | null;
  startTime?: Date | null;
  endTime?: Date | null;
  location?: string | null;
  track?: 'main' | 'workshop-a' | 'workshop-b' | null;
  createdAt: Date;
  updatedAt: Date;
};

export type Speakers = {
  id: string;
  name: string;
  slug?: string | null;
  photo?: string | null;
  jobTitle?: string | null;
  company?: string | null;
  bio?: string | null;
  shortBio?: string | null;
  socialLinks?: {
    twitter?: string | null;
    linkedin?: string | null;
    website?: string | null;
  } | null;
  featured?: boolean | null;
  sessions?: string[] | null;
  createdAt: Date;
  updatedAt: Date;
};

export type Sponsors = {
  id: string;
  name: string;
  logo?: string | null;
  tier: 'platinum' | 'gold' | 'silver' | 'bronze' | 'partner';
  website?: string | null;
  description?: string | null;
  featured?: boolean | null;
  createdAt: Date;
  updatedAt: Date;
};

export type Users = {
  id: string;
  name: string;
  role: 'admin' | 'editor';
  createdAt: Date;
  updatedAt: Date;
};

export type EventSettings = {
  id: string;
  eventName: string;
  eventDate?: Date | null;
  venue?: {
    name?: string | null;
    address?: string | null;
    city?: string | null;
  } | null;
  registrationUrl?: string | null;
  heroImage?: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type PayloadGeneratedTypes = {
  collections: {
    media: Media;
    speakers: Speakers;
    sponsors: Sponsors;
    sessions: Sessions;
    users: Users;
  };
  globals: {
    'event-settings': EventSettings;
  };
};